# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9754835d3606b19c62ff3400e0f13adc82097f978fafcc82a8a41f5caa04f0700c501774b801ec0cf47892f02c03f79055764a73a8c9a6b66c69429baf027ae

test:
  secret_key_base: aceb6fb1d34e7295edb7343d6bd560520e1886e0efc894253205a9409ee2a72d6954b79043187456236bf87e7a7084d67cc6f78a18f9f72aa9eec57a0c379200

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
